//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties
    {
        public long product_id { get; set; }
        public string attribute { get; set; }
        public string value { get; set; }
        public long property_id { get; set; }
    
        public virtual products products { get; set; }
    }
}
